services:
  db:
    image: mysql:8.0
    container_name: lv3-db
    environment:
      MYSQL_DATABASE: woowabowling
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

volumes:
  db-data:
