name: dev-cd

on:
  push:
    branches:
      - develop   # main 브랜치 푸시 시 배포

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 세팅 (Spring Boot 빌드용)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Spring Boot JAR 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. 배포 스크립트 실행 (EC2 안에서 직접 실행)
      - name: Execute deploy script
        run: |
          chmod +x /home/ubuntu/app/deploy.sh
          /home/ubuntu/app/deploy.sh
